Repository OCA/sale-reporting, pull requests merged in 2020-04, with the labels that each got.

#85 [ADD] sale_report_country_state: New module
  sale_report_country_state/__init__.py
  sale_report_country_state/__manifest__.py
  sale_report_country_state/i18n/es.po
  sale_report_country_state/i18n/sale_report_state_filter.pot
  sale_report_country_state/readme/CONTRIBUTORS.rst
  sale_report_country_state/readme/DESCRIPTION.rst
  sale_report_country_state/readme/USAGE.rst
  sale_report_country_state/reports/__init__.py
  sale_report_country_state/reports/report_all_channels_sales.py
  sale_report_country_state/reports/sale_report.py
  sale_report_country_state/reports/sale_report_views.xml
Labels: approved, bot is merging ⏳, needs review

#92 [MIG] sale_report_country_state: Migration to 12.0
  sale_report_country_state/README.rst
  sale_report_country_state/__init__.py
  sale_report_country_state/__manifest__.py
  sale_report_country_state/i18n/es.po
  sale_report_country_state/i18n/sale_report_country_state.pot
  sale_report_country_state/i18n/sale_report_state_filter.pot
  sale_report_country_state/readme/CONTRIBUTORS.rst
  sale_report_country_state/readme/DESCRIPTION.rst
  sale_report_country_state/readme/USAGE.rst
  sale_report_country_state/reports/__init__.py
  sale_report_country_state/reports/report_all_channels_sales.py
  sale_report_country_state/reports/sale_report.py
  sale_report_country_state/reports/sale_report_views.xml
  sale_report_country_state/static/description/icon.png
  sale_report_country_state/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#94 [10.0][IMP] travis: Update to latest template
  .travis.yml
Labels: bot is merging ⏳
