Repository OCA/sale-reporting, pull requests merged in 2021-05, with the labels that each got.

#101 [14.0][ADD] sale_outgoing_product: Add new module to show products to be delivered in sales
  sale_outgoing_product/README.rst
  sale_outgoing_product/__init__.py
  sale_outgoing_product/__manifest__.py
  sale_outgoing_product/readme/CONTRIBUTORS.rst
  sale_outgoing_product/readme/DESCRIPTION.rst
  sale_outgoing_product/readme/USAGE.rst
  sale_outgoing_product/static/description/icon.png
  sale_outgoing_product/static/description/index.html
  sale_outgoing_product/views/stock_move_views.xml
  setup/sale_outgoing_product/odoo/addons/sale_outgoing_product
  setup/sale_outgoing_product/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#77 [13.0][IMP] sale_layount_category_hide_detail hidding amounts
  sale_layout_category_hide_detail/models/account_move.py
  sale_layout_category_hide_detail/models/sale_order.py
  sale_layout_category_hide_detail/views/account_move_view.xml
  sale_layout_category_hide_detail/views/sale_order_report_templates.xml
  sale_layout_category_hide_detail/views/sale_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs fixing, ready to merge

#112 [13.0][MIG] sale_report_country_state: Migration to 13.0
  sale_report_country_state/README.rst
  sale_report_country_state/__init__.py
  sale_report_country_state/__manifest__.py
  sale_report_country_state/i18n/es.po
  sale_report_country_state/i18n/sale_report_country_state.pot
  sale_report_country_state/i18n/sale_report_state_filter.pot
  sale_report_country_state/readme/CONTRIBUTORS.rst
  sale_report_country_state/readme/DESCRIPTION.rst
  sale_report_country_state/readme/USAGE.rst
  sale_report_country_state/reports/__init__.py
  sale_report_country_state/reports/report_all_channels_sales.py
  sale_report_country_state/reports/sale_report.py
  sale_report_country_state/reports/sale_report_views.xml
  sale_report_country_state/static/description/icon.png
  sale_report_country_state/static/description/index.html
  setup/sale_report_country_state/odoo/addons/sale_report_country_state
  setup/sale_report_country_state/setup.py
Labels: approved, bot is merging ⏳

#105 [13.0][MIG] sale_comment_template: Migration 13.0
  oca_dependencies.txt
  sale_comment_template/README.rst
  sale_comment_template/__init__.py
  sale_comment_template/__manifest__.py
  sale_comment_template/i18n/de.po
  sale_comment_template/i18n/es.po
  sale_comment_template/i18n/fr.po
  sale_comment_template/i18n/it.po
  sale_comment_template/i18n/pt.po
  sale_comment_template/i18n/sale_comment_template.pot
  sale_comment_template/migrations/13.0.1.0.0/post-migration.py
  sale_comment_template/migrations/13.0.1.0.0/pre-migration.py
  sale_comment_template/models/__init__.py
  sale_comment_template/models/sale_order.py
  sale_comment_template/readme/CONTRIBUTORS.rst
  sale_comment_template/readme/DESCRIPTION.rst
  sale_comment_template/readme/INSTALL.rst
  sale_comment_template/security/ir.model.access.csv
  sale_comment_template/static/description/icon.png
  sale_comment_template/static/description/index.html
  sale_comment_template/tests/__init__.py
  sale_comment_template/tests/test_sale_order_report.py
  sale_comment_template/views/base_comment_template_view.xml
  sale_comment_template/views/report_saleorder.xml
  sale_comment_template/views/sale_order_view.xml
  setup/sale_comment_template/odoo/addons/sale_comment_template
  setup/sale_comment_template/setup.py
Labels: approved, bot is merging ⏳

#113 [14.0][IMP] sale_comment_template: Include changes from 13.0
  sale_comment_template/__manifest__.py
  sale_comment_template/models/sale_order.py
  sale_comment_template/readme/CONTRIBUTORS.rst
  sale_comment_template/readme/DESCRIPTION.rst
  sale_comment_template/static/src/css/sale.css
  sale_comment_template/tests/test_sale_order_report.py
  sale_comment_template/views/base_comment_template_view.xml
  sale_comment_template/views/report_saleorder.xml
  sale_comment_template/views/sale_order_view.xml
Labels: approved, bot is merging ⏳
