Repository OCA/sale-reporting, pull requests merged in 2022-11, with the labels that each got.

#184 [IMP][14.0] sale_comment_template: revert of PR #175
  sale_comment_template/models/__init__.py
  sale_comment_template/models/base_comment_template.py
  sale_comment_template/readme/CONTRIBUTORS.rst
  sale_comment_template/views/base_comment_template_view.xml
Labels: approved, bot is merging ⏳

#186 [14.0][FIX] sale_comment_template: Change assertRegexpMatches to assertRegex to remove the warning.
  sale_comment_template/tests/test_sale_order_report.py
Labels: bot is merging ⏳

#183 [14.0][MIG] sale_report_delivered_brand: Migration to 14.0
  sale_report_delivered/tests/test_sale_report_delivered.py
  sale_report_delivered_brand/README.rst
  sale_report_delivered_brand/__init__.py
  sale_report_delivered_brand/__manifest__.py
  sale_report_delivered_brand/i18n/es.po
  sale_report_delivered_brand/i18n/sale_report_delivered_brand.pot
  sale_report_delivered_brand/models/__init__.py
  sale_report_delivered_brand/models/sale_report_delivered.py
  sale_report_delivered_brand/readme/CONTRIBUTORS.rst
  sale_report_delivered_brand/readme/DESCRIPTION.rst
  sale_report_delivered_brand/readme/USAGE.rst
  sale_report_delivered_brand/static/description/icon.png
  sale_report_delivered_brand/static/description/index.html
  sale_report_delivered_brand/tests/__init__.py
  sale_report_delivered_brand/tests/test_sale_report_delivered_brand.py
  sale_report_delivered_brand/views/sale_report_delivered_views.xml
  setup/sale_report_delivered_brand/odoo/addons/sale_report_delivered_brand
  setup/sale_report_delivered_brand/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#147 [13.0][ADD] sale_report_delivered_partner_priority: New module to filter by priority on sale_report_delivered
  oca_dependencies.txt
  sale_report_delivered_partner_priority/README.rst
  sale_report_delivered_partner_priority/__init__.py
  sale_report_delivered_partner_priority/__manifest__.py
  sale_report_delivered_partner_priority/i18n/es.po
  sale_report_delivered_partner_priority/i18n/sale_report_delivered_partner_priority.pot
  sale_report_delivered_partner_priority/models/__init__.py
  sale_report_delivered_partner_priority/models/sale_report_delivered.py
  sale_report_delivered_partner_priority/readme/CONTRIBUTORS.rst
  sale_report_delivered_partner_priority/readme/DESCRIPTION.rst
  sale_report_delivered_partner_priority/readme/USAGE.rst
  sale_report_delivered_partner_priority/static/description/index.html
  sale_report_delivered_partner_priority/views/sale_report_delivered_views.xml
  setup/sale_report_delivered_partner_priority/odoo/addons/sale_report_delivered_partner_priority
  setup/sale_report_delivered_partner_priority/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#176 [13.0][FIX] product_sold_by_delivery_week: fix singleton in context
  product_sold_by_delivery_week/models/sale_order.py
Labels: approved, bot is merging ⏳

#191 [13.0][FIX] product_sold_by_delivery_week: Fix key error when product not in dict
  product_sold_by_delivery_week/models/sale_order.py
Labels: approved, bot is merging ⏳

#188 [15.0][MIG] sale_report_delivered: Migration to version 15.0
  sale_report_delivered/README.rst
  sale_report_delivered/__init__.py
  sale_report_delivered/__manifest__.py
  sale_report_delivered/i18n/es.po
  sale_report_delivered/i18n/sale_report_delivered.pot
  sale_report_delivered/readme/CONTRIBUTORS.rst
  sale_report_delivered/readme/DESCRIPTION.rst
  sale_report_delivered/readme/USAGE.rst
  sale_report_delivered/reports/__init__.py
  sale_report_delivered/reports/sale_report.py
  sale_report_delivered/security/ir.model.access.csv
  sale_report_delivered/static/description/icon.png
  sale_report_delivered/static/description/index.html
  sale_report_delivered/tests/__init__.py
  sale_report_delivered/tests/test_sale_report_delivered.py
  sale_report_delivered/views/sale_report_delivered_views.xml
  setup/sale_report_delivered/odoo/addons/sale_report_delivered
  setup/sale_report_delivered/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#193 [15.0][ADD] sale_report_delivered_volume: New module to show the delivered volume at sale.report
  sale_report_delivered_volume/README.rst
  sale_report_delivered_volume/__init__.py
  sale_report_delivered_volume/__manifest__.py
  sale_report_delivered_volume/i18n/es.po
  sale_report_delivered_volume/i18n/sale_report_delivered_volume.pot
  sale_report_delivered_volume/models/__init__.py
  sale_report_delivered_volume/models/sale_report.py
  sale_report_delivered_volume/readme/CONTRIBUTORS.rst
  sale_report_delivered_volume/readme/DESCRIPTION.rst
  sale_report_delivered_volume/readme/USAGE.rst
  sale_report_delivered_volume/static/description/icon.png
  sale_report_delivered_volume/static/description/index.html
  setup/sale_report_delivered_volume/odoo/addons/sale_report_delivered_volume
  setup/sale_report_delivered_volume/setup.py
Labels: approved, bot is merging ⏳

#116 [14.0][MIG] sale_backorder
  .pre-commit-config.yaml
  sale_backorder/README.rst
  sale_backorder/__init__.py
  sale_backorder/__manifest__.py
  sale_backorder/i18n/de.po
  sale_backorder/i18n/sale_backorder.pot
  sale_backorder/i18n/sl.po
  sale_backorder/models/__init__.py
  sale_backorder/models/sale.py
  sale_backorder/models/sale_order_line.py
  sale_backorder/readme/CONTRIBUTORS.rst
  sale_backorder/readme/CREDITS.rst
  sale_backorder/readme/DESCRIPTION.rst
  sale_backorder/readme/USAGE.rst
  sale_backorder/report/so_backorder_report.xml
  sale_backorder/security/ir.model.access.csv
  sale_backorder/static/description/icon.png
  sale_backorder/static/description/index.html
  sale_backorder/tests/__init__.py
  sale_backorder/tests/test_sale_backorder.py
  sale_backorder/views/sale_view.xml
  sale_backorder/views/so_backorder_view.xml
  sale_backorder/wizard/__init__.py
  sale_backorder/wizard/so_backorder_wizard.py
  sale_backorder/wizard/so_backorder_wizard_view.xml
  setup/sale_backorder/odoo/addons/sale_backorder
  setup/sale_backorder/setup.py
Labels: needs review, migration, bot is merging ⏳

#195 [14.0] sale_order_line_position: split recompute_positions
  sale_order_line_position/models/sale_order.py
Labels: bot is merging ⏳
