Repository OCA/sale-reporting, pull requests merged in 2022-10, with the labels that each got.

#144 [15.0] add sale_multicompany_reporting_currency
  sale_multicompany_reporting_currency/README.rst
  sale_multicompany_reporting_currency/__init__.py
  sale_multicompany_reporting_currency/__manifest__.py
  sale_multicompany_reporting_currency/i18n/sale_multicompany_reporting_currency.pot
  sale_multicompany_reporting_currency/models/__init__.py
  sale_multicompany_reporting_currency/models/res_company.py
  sale_multicompany_reporting_currency/models/res_config_settings.py
  sale_multicompany_reporting_currency/models/sale_order.py
  sale_multicompany_reporting_currency/readme/CONTRIBUTORS.rst
  sale_multicompany_reporting_currency/readme/DESCRIPTION.rst
  sale_multicompany_reporting_currency/static/description/icon.png
  sale_multicompany_reporting_currency/static/description/index.html
  sale_multicompany_reporting_currency/tests/__init__.py
  sale_multicompany_reporting_currency/tests/test_amount_multicompany_reporting_currency.py
  sale_multicompany_reporting_currency/views/res_config_settings_views.xml
  sale_multicompany_reporting_currency/views/sale_order_views.xml
  setup/sale_multicompany_reporting_currency/odoo/addons/sale_multicompany_reporting_currency
  setup/sale_multicompany_reporting_currency/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#155 [14.0] [ADD] `sale_order_invoice_date` : Display the invoice date on Sales Order analysis reports
  sale_order_invoice_date/__init__.py
  sale_order_invoice_date/__manifest__.py
  sale_order_invoice_date/hooks.py
  sale_order_invoice_date/i18n/fr.po
  sale_order_invoice_date/models/__init__.py
  sale_order_invoice_date/models/sale_order.py
  sale_order_invoice_date/models/sale_order_line.py
  sale_order_invoice_date/readme/CONTRIBUTORS.rst
  sale_order_invoice_date/readme/DESCRIPTION.rst
  sale_order_invoice_date/reports/__init__.py
  sale_order_invoice_date/reports/sale_report.py
  sale_order_invoice_date/reports/sale_report.xml
  sale_order_invoice_date/tests/__init__.py
  sale_order_invoice_date/tests/test_sale_order_invoice_date.py
  setup/sale_order_invoice_date/odoo/addons/sale_order_invoice_date
  setup/sale_order_invoice_date/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#164 [15.0] [MIG] `sale_order_report_product_image` : Migration to 15.0
  sale_order_report_product_image/README.rst
  sale_order_report_product_image/__init__.py
  sale_order_report_product_image/__manifest__.py
  sale_order_report_product_image/i18n/de.po
  sale_order_report_product_image/i18n/es.po
  sale_order_report_product_image/i18n/it.po
  sale_order_report_product_image/i18n/sale_order_report_product_image.pot
  sale_order_report_product_image/readme/CONTRIBUTORS.rst
  sale_order_report_product_image/readme/DESCRIPTION.rst
  sale_order_report_product_image/readme/INSTALL.rst
  sale_order_report_product_image/readme/USAGE.rst
  sale_order_report_product_image/static/description/icon.png
  sale_order_report_product_image/static/description/index.html
  sale_order_report_product_image/views/report_saleorder.xml
  setup/sale_order_report_product_image/odoo/addons/sale_order_report_product_image
  setup/sale_order_report_product_image/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#156 [14.0] [ADD] `sale_report_commitment_date` : Display the commitment date on Sales Order analysis reports
  sale_report_commitment_date/__init__.py
  sale_report_commitment_date/__manifest__.py
  sale_report_commitment_date/i18n/fr.po
  sale_report_commitment_date/readme/CONTRIBUTORS.rst
  sale_report_commitment_date/readme/DESCRIPTION.rst
  sale_report_commitment_date/reports/__init__.py
  sale_report_commitment_date/reports/sale_report.py
  sale_report_commitment_date/reports/sale_report.xml
  setup/sale_report_commitment_date/odoo/addons/sale_report_commitment_date
  setup/sale_report_commitment_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#157 [14.0] [ADD] `sale_report_delivery_date` : Display the last delivery date on Sales Order analysis reports
  sale_report_delivery_date/__init__.py
  sale_report_delivery_date/__manifest__.py
  sale_report_delivery_date/i18n/fr.po
  sale_report_delivery_date/readme/CONTRIBUTORS.rst
  sale_report_delivery_date/readme/DESCRIPTION.rst
  sale_report_delivery_date/reports/__init__.py
  sale_report_delivery_date/reports/sale_report.py
  sale_report_delivery_date/reports/sale_report.xml
  sale_report_delivery_date/tests/__init__.py
  sale_report_delivery_date/tests/test_sale_report.py
  setup/sale_report_delivery_date/odoo/addons/sale_report_delivery_date
  setup/sale_report_delivery_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#148 [12.0] FIX sale_comment_template opening popup for sale order line, otherwise formatted_note field is not usable
  sale_comment_template/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#146 [13.0][ADD] sale_report_delivered_brand: New module to filter by brand on sale_report_delivered
  sale_report_delivered_brand/README.rst
  sale_report_delivered_brand/__init__.py
  sale_report_delivered_brand/__manifest__.py
  sale_report_delivered_brand/i18n/es.po
  sale_report_delivered_brand/i18n/sale_report_delivered_brand.pot
  sale_report_delivered_brand/models/__init__.py
  sale_report_delivered_brand/models/sale_report_delivered.py
  sale_report_delivered_brand/readme/CONTRIBUTORS.rst
  sale_report_delivered_brand/readme/DESCRIPTION.rst
  sale_report_delivered_brand/readme/USAGE.rst
  sale_report_delivered_brand/static/description/index.html
  sale_report_delivered_brand/views/sale_report_delivered_views.xml
  setup/sale_report_delivered_brand/odoo/addons/sale_report_delivered_brand
  setup/sale_report_delivered_brand/setup.py
Labels: bot is merging ⏳, stale

#145 [15.0] Migration of sale_comment_template
  sale_comment_template/README.rst
  sale_comment_template/__init__.py
  sale_comment_template/__manifest__.py
  sale_comment_template/i18n/de.po
  sale_comment_template/i18n/es.po
  sale_comment_template/i18n/fr.po
  sale_comment_template/i18n/it.po
  sale_comment_template/i18n/pt.po
  sale_comment_template/i18n/sale_comment_template.pot
  sale_comment_template/models/__init__.py
  sale_comment_template/models/sale_order.py
  sale_comment_template/readme/CONTRIBUTORS.rst
  sale_comment_template/readme/DESCRIPTION.rst
  sale_comment_template/readme/INSTALL.rst
  sale_comment_template/security/ir.model.access.csv
  sale_comment_template/static/description/icon.png
  sale_comment_template/static/description/index.html
  sale_comment_template/tests/__init__.py
  sale_comment_template/tests/test_sale_order_report.py
  sale_comment_template/views/base_comment_template_view.xml
  sale_comment_template/views/report_saleorder.xml
  sale_comment_template/views/sale_order_view.xml
  setup/sale_comment_template/odoo/addons/sale_comment_template
  setup/sale_comment_template/setup.py
Labels: bot is merging ⏳

#175 [IMP][14.0] sale_comment_template
  sale_comment_template/models/__init__.py
  sale_comment_template/models/base_comment_template.py
  sale_comment_template/readme/CONTRIBUTORS.rst
  sale_comment_template/views/base_comment_template_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
