Repository OCA/sale-reporting, pull requests merged in 2022-09, with the labels that each got.

#165 [MIG] sale_report_delivered_subtotal: Migration to 14.0
  sale_report_delivered_subtotal/README.rst
  sale_report_delivered_subtotal/__init__.py
  sale_report_delivered_subtotal/__manifest__.py
  sale_report_delivered_subtotal/i18n/es.po
  sale_report_delivered_subtotal/i18n/sale_report_delivered_subtotal.pot
  sale_report_delivered_subtotal/readme/CONTRIBUTORS.rst
  sale_report_delivered_subtotal/readme/DESCRIPTION.rst
  sale_report_delivered_subtotal/readme/USAGE.rst
  sale_report_delivered_subtotal/reports/__init__.py
  sale_report_delivered_subtotal/reports/sale_report.py
  sale_report_delivered_subtotal/static/description/icon.png
  sale_report_delivered_subtotal/static/description/index.html
  setup/sale_report_delivered_subtotal/odoo/addons/sale_report_delivered_subtotal
  setup/sale_report_delivered_subtotal/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#170 [14.0][MIG] sale_layout_category_hide_detail: Migration to 14.0
  sale_layout_category_hide_detail/README.rst
  sale_layout_category_hide_detail/__init__.py
  sale_layout_category_hide_detail/__manifest__.py
  sale_layout_category_hide_detail/i18n/es.po
  sale_layout_category_hide_detail/i18n/sale_layout_category_hide_detail.pot
  sale_layout_category_hide_detail/models/__init__.py
  sale_layout_category_hide_detail/models/account_move.py
  sale_layout_category_hide_detail/models/sale_order.py
  sale_layout_category_hide_detail/readme/CONTRIBUTORS.rst
  sale_layout_category_hide_detail/readme/DESCRIPTION.rst
  sale_layout_category_hide_detail/readme/ROADMAP.rst
  sale_layout_category_hide_detail/readme/USAGE.rst
  sale_layout_category_hide_detail/static/description/icon.png
  sale_layout_category_hide_detail/static/description/index.html
  sale_layout_category_hide_detail/static/description/readme-icons/eye-slash.png
  sale_layout_category_hide_detail/static/description/readme-icons/eye.png
  sale_layout_category_hide_detail/static/description/readme-icons/minus-circle.png
  sale_layout_category_hide_detail/static/description/readme-icons/plus-circle.png
  sale_layout_category_hide_detail/static/src/js/boolean_fa_icon_widget.js
  sale_layout_category_hide_detail/static/src/js/hide_details_translations.js
  sale_layout_category_hide_detail/static/src/js/sale_layout_category_hide_detail.js
  sale_layout_category_hide_detail/tests/__init__.py
  sale_layout_category_hide_detail/tests/test_sale_layout_category_hide_detail.py
  sale_layout_category_hide_detail/views/account_move_view.xml
  sale_layout_category_hide_detail/views/assets.xml
  sale_layout_category_hide_detail/views/invoice_report_templates.xml
  sale_layout_category_hide_detail/views/sale_order_report_templates.xml
  sale_layout_category_hide_detail/views/sale_portal_templates.xml
  sale_layout_category_hide_detail/views/sale_views.xml
  setup/sale_layout_category_hide_detail/odoo/addons/sale_layout_category_hide_detail
  setup/sale_layout_category_hide_detail/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#171 [14.0][FIX] sale_layout_category_hide_detail: Set the correct URL of the icons in readme.
  sale_layout_category_hide_detail/README.rst
  sale_layout_category_hide_detail/readme/USAGE.rst
  sale_layout_category_hide_detail/static/description/index.html
Labels: bot is merging ⏳

#172 [14.0][FIX] sale_layout_category_hide_detail: Remove unused code.
  sale_layout_category_hide_detail/static/src/js/boolean_fa_icon_widget.js
Labels: approved, bot is merging ⏳
