Repository OCA/sale-reporting, pull requests merged in 2023-09, with the labels that each got.

#230 [BUILD] template update
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳

#231 [ADD] sale_packaging_report: packaging data in sale reports
  sale_packaging_report/README.rst
  sale_packaging_report/__init__.py
  sale_packaging_report/__manifest__.py
  sale_packaging_report/i18n/es.po
  sale_packaging_report/i18n/sale_packaging_report.pot
  sale_packaging_report/readme/CONFIGURE.rst
  sale_packaging_report/readme/CONTRIBUTORS.rst
  sale_packaging_report/readme/DESCRIPTION.rst
  sale_packaging_report/readme/USAGE.rst
  sale_packaging_report/report/__init__.py
  sale_packaging_report/report/sale_report.py
  sale_packaging_report/report/sale_report_view.xml
  sale_packaging_report/static/description/icon.png
  sale_packaging_report/static/description/index.html
  sale_packaging_report/views/report_sale_order.xml
  setup/sale_packaging_report/odoo/addons/sale_packaging_report
  setup/sale_packaging_report/setup.py
Labels: enhancement, approved, bot is merging ⏳

#227 [16.0][IMP] sale_comment_template: allow to use dynamic information in template
  sale_comment_template/views/report_saleorder.xml
Labels: approved, ready to merge, bot is merging ⏳
