Repository OCA/sale-reporting, pull requests merged in 2023-02, with the labels that each got.

#213 [15.0] Update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: needs review

#209 [15.0][FIX] sale_multicompany_reporting_currency: Fix multicompany_reporting_currency_rate calculation
  sale_multicompany_reporting_currency/__manifest__.py
  sale_multicompany_reporting_currency/models/sale_order.py
  sale_multicompany_reporting_currency/tests/test_amount_multicompany_reporting_currency.py
Labels: approved

#167 [15.0] [ADD] `sale_order_report_customer_lead` : Show the lead time on sale order and quotation reports
  sale_order_report_customer_lead/README.rst
  sale_order_report_customer_lead/__init__.py
  sale_order_report_customer_lead/__manifest__.py
  sale_order_report_customer_lead/readme/CONTRIBUTORS.rst
  sale_order_report_customer_lead/readme/DESCRIPTION.rst
  sale_order_report_customer_lead/reports/templates.xml
  setup/sale_order_report_customer_lead/odoo/addons/sale_order_report_customer_lead
  setup/sale_order_report_customer_lead/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#214 [16.0] Update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: needs review

#211 [MIG] sale_order_line_position: Migration to 16.0
  sale_order_line_position/README.rst
  sale_order_line_position/__init__.py
  sale_order_line_position/__manifest__.py
  sale_order_line_position/i18n/ca.po
  sale_order_line_position/i18n/de.po
  sale_order_line_position/i18n/sale_order_line_position.pot
  sale_order_line_position/models/__init__.py
  sale_order_line_position/models/ir_actions_report.py
  sale_order_line_position/models/res_company.py
  sale_order_line_position/models/res_config_settings.py
  sale_order_line_position/models/sale_order.py
  sale_order_line_position/models/sale_order_line.py
  sale_order_line_position/readme/CONTRIBUTORS.rst
  sale_order_line_position/readme/CREDITS.rst
  sale_order_line_position/readme/DESCRIPTION.rst
  sale_order_line_position/readme/ROADMAP.rst
  sale_order_line_position/report/sale_order_report.xml
  sale_order_line_position/static/description/icon.png
  sale_order_line_position/static/description/index.html
  sale_order_line_position/tests/__init__.py
  sale_order_line_position/tests/test_sale_order_line_position.py
  sale_order_line_position/views/res_config_settings.xml
  sale_order_line_position/views/sale_order.xml
  setup/sale_order_line_position/odoo/addons/sale_order_line_position
  setup/sale_order_line_position/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#180 [ADD] configuration files
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  README.md.rej
  sale_comment_template/__manifest__.py
  sale_layout_category_hide_detail/__manifest__.py
Labels: bot is merging ⏳, stale
