Repository OCA/sale-reporting, pull requests merged in 2024-06, with the labels that each got.

#272 [FIX] [16.0] sale_packaging_report: Do not cut packaging text on reports
  sale_packaging_report/views/report_sale_order.xml
Labels: needs review, approved, bot is merging ⏳

#271 [FIX] [16.0] sale_report_delivered: Consider 0.0 Value valuation layers
  sale_report_delivered/reports/sale_report.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#275 [FIX] [16.0] sale_report_delivered: Calculate Dropship moves too
  sale_report_delivered/README.rst
  sale_report_delivered/readme/CONTRIBUTORS.rst
  sale_report_delivered/readme/DESCRIPTION.rst
  sale_report_delivered/reports/sale_report.py
  sale_report_delivered/static/description/index.html
Labels: approved, bot is merging ⏳

#276 [16.0][FIX] sale_layout_category_hide_detail: Full width to note lines
  sale_layout_category_hide_detail/static/src/js/sale_layout_category_hide_detail.esm.js
Labels: approved, bot is merging ⏳
