Repository OCA/sale-reporting, pull requests merged in 2024-02, with the labels that each got.

#249 [15.0][ADD] sale_report_salesman: Allow all sales groups access to reporting sales
  sale_report_salesman/README.rst
  sale_report_salesman/__init__.py
  sale_report_salesman/__manifest__.py
  sale_report_salesman/hooks.py
  sale_report_salesman/i18n/es.po
  sale_report_salesman/i18n/sale_report_salesman.pot
  sale_report_salesman/readme/CONTRIBUTORS.rst
  sale_report_salesman/readme/DESCRIPTION.rst
  sale_report_salesman/static/description/icon.png
  sale_report_salesman/static/description/index.html
  sale_report_salesman/tests/__init__.py
  sale_report_salesman/tests/test_uninstall_hook.py
  sale_report_salesman/views/menu_views.xml
  setup/sale_report_salesman/odoo/addons/sale_report_salesman
  setup/sale_report_salesman/setup.py
Labels: approved, bot is merging ⏳

#251 [15.0][FIX] sale_report_salesman: import hooks init file
  sale_report_salesman/README.rst
  sale_report_salesman/__init__.py
  sale_report_salesman/__manifest__.py
  sale_report_salesman/static/description/index.html
Labels: bot is merging ⏳

#252 [FIX] product_sold_by_delivery_week: work with lower permissions
  product_sold_by_delivery_week/README.rst
  product_sold_by_delivery_week/models/product_product.py
  product_sold_by_delivery_week/models/stock_move.py
  product_sold_by_delivery_week/readme/CONTRIBUTORS.rst
  product_sold_by_delivery_week/readme/ROADMAP.rst
  product_sold_by_delivery_week/readme/USAGE.rst
  product_sold_by_delivery_week/static/description/index.html
  product_sold_by_delivery_week/tests/test_product_sold_by_delivery_week.py
Labels: bug, approved, bot is merging ⏳
