Repository OCA/sale-reporting, pull requests merged in 2025-02, with the labels that each got.

#307 [18.0][MIG] sale_report_salesperson_from_partner: Migration to 18.0
  sale_report_salesperson_from_partner/README.rst
  sale_report_salesperson_from_partner/__init__.py
  sale_report_salesperson_from_partner/__manifest__.py
  sale_report_salesperson_from_partner/i18n/es.po
  sale_report_salesperson_from_partner/i18n/it.po
  sale_report_salesperson_from_partner/i18n/sale_report_salesperson_from_partner.pot
  sale_report_salesperson_from_partner/pyproject.toml
  sale_report_salesperson_from_partner/readme/CONTRIBUTORS.md
  sale_report_salesperson_from_partner/readme/DESCRIPTION.md
  sale_report_salesperson_from_partner/report/__init__.py
  sale_report_salesperson_from_partner/report/sale_report.py
  sale_report_salesperson_from_partner/static/description/icon.png
  sale_report_salesperson_from_partner/static/description/index.html
  sale_report_salesperson_from_partner/tests/__init__.py
  sale_report_salesperson_from_partner/tests/test_sale_report_salesperson_from_partner.py
  sale_report_salesperson_from_partner/views/sale_report_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#314 [18.0][MIG] sale_report_delivered: Migration to version 18.0
  sale_report_delivered/README.rst
  sale_report_delivered/__init__.py
  sale_report_delivered/__manifest__.py
  sale_report_delivered/i18n/es.po
  sale_report_delivered/i18n/it.po
  sale_report_delivered/i18n/sale_report_delivered.pot
  sale_report_delivered/pyproject.toml
  sale_report_delivered/readme/CONTRIBUTORS.md
  sale_report_delivered/readme/DESCRIPTION.md
  sale_report_delivered/readme/USAGE.md
  sale_report_delivered/reports/__init__.py
  sale_report_delivered/reports/sale_report_delivered.py
  sale_report_delivered/security/ir.model.access.csv
  sale_report_delivered/security/sale_report_security.xml
  sale_report_delivered/static/description/icon.png
  sale_report_delivered/static/description/index.html
  sale_report_delivered/tests/__init__.py
  sale_report_delivered/tests/test_sale_report_delivered.py
  sale_report_delivered/views/sale_report_delivered_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#317 [18.0][MIG] sale_report_delivered_brand: Migration to 18.0
  sale_report_delivered_brand/README.rst
  sale_report_delivered_brand/__init__.py
  sale_report_delivered_brand/__manifest__.py
  sale_report_delivered_brand/i18n/es.po
  sale_report_delivered_brand/i18n/sale_report_delivered_brand.pot
  sale_report_delivered_brand/models/__init__.py
  sale_report_delivered_brand/models/sale_report_delivered.py
  sale_report_delivered_brand/pyproject.toml
  sale_report_delivered_brand/readme/CONTRIBUTORS.md
  sale_report_delivered_brand/readme/DESCRIPTION.md
  sale_report_delivered_brand/readme/USAGE.md
  sale_report_delivered_brand/static/description/icon.png
  sale_report_delivered_brand/static/description/index.html
  sale_report_delivered_brand/tests/__init__.py
  sale_report_delivered_brand/tests/test_sale_report_delivered_brand.py
  sale_report_delivered_brand/views/sale_report_delivered_views.xml
Labels: approved, bot is merging ⏳

#318 [16.0] [ADD] sale_report_delivered_attribute_values
  sale_report_delivered_attribute_values/README.rst
  sale_report_delivered_attribute_values/__init__.py
  sale_report_delivered_attribute_values/__manifest__.py
  sale_report_delivered_attribute_values/i18n/es.po
  sale_report_delivered_attribute_values/i18n/sale_report_delivered_attribute_values.pot
  sale_report_delivered_attribute_values/readme/CONTEXT.md
  sale_report_delivered_attribute_values/readme/CONTRIBUTORS.md
  sale_report_delivered_attribute_values/readme/CREDITS.md
  sale_report_delivered_attribute_values/readme/DESCRIPTION.md
  sale_report_delivered_attribute_values/readme/USAGE.md
  sale_report_delivered_attribute_values/report/__init__.py
  sale_report_delivered_attribute_values/report/sale_report.py
  sale_report_delivered_attribute_values/static/description/icon.png
  sale_report_delivered_attribute_values/static/description/index.html
  sale_report_delivered_attribute_values/tests/__init__.py
  sale_report_delivered_attribute_values/tests/test_sale_report_delivered_attribute_values.py
  sale_report_delivered_attribute_values/views/sale_report_delivered_views.xml
  setup/sale_report_delivered_attribute_values/odoo/addons/sale_report_delivered_attribute_values
  setup/sale_report_delivered_attribute_values/setup.py
Labels: work in progress, approved, ready to merge, bot is merging ⏳

#319 [17.0][MIG] sale_report_salesman: Migration to 17.0
  sale_report_salesman/README.rst
  sale_report_salesman/__init__.py
  sale_report_salesman/__manifest__.py
  sale_report_salesman/hooks.py
  sale_report_salesman/i18n/es.po
  sale_report_salesman/i18n/sale_report_salesman.pot
  sale_report_salesman/pyproject.toml
  sale_report_salesman/readme/CONTRIBUTORS.md
  sale_report_salesman/readme/DESCRIPTION.md
  sale_report_salesman/static/description/icon.png
  sale_report_salesman/static/description/index.html
  sale_report_salesman/tests/__init__.py
  sale_report_salesman/tests/test_uninstall_hook.py
  sale_report_salesman/views/menu_views.xml
Labels: approved, bot is merging ⏳
