Repository OCA/sale-reporting, pull requests merged in 2025-03, with the labels that each got.

#320 [18.0][MIG] sale_report_delivered_partner_priority: Migration to 18.0
  sale_report_delivered_partner_priority/README.rst
  sale_report_delivered_partner_priority/__init__.py
  sale_report_delivered_partner_priority/__manifest__.py
  sale_report_delivered_partner_priority/i18n/es.po
  sale_report_delivered_partner_priority/i18n/sale_report_delivered_partner_priority.pot
  sale_report_delivered_partner_priority/models/__init__.py
  sale_report_delivered_partner_priority/models/sale_report_delivered.py
  sale_report_delivered_partner_priority/pyproject.toml
  sale_report_delivered_partner_priority/readme/CONTRIBUTORS.md
  sale_report_delivered_partner_priority/readme/DESCRIPTION.md
  sale_report_delivered_partner_priority/readme/USAGE.md
  sale_report_delivered_partner_priority/static/description/icon.png
  sale_report_delivered_partner_priority/static/description/index.html
  sale_report_delivered_partner_priority/views/sale_report_delivered_views.xml
Labels: approved, bot is merging ⏳

#322 [16.0][FIX] sale_layout_category_hide_detail: Post-install test + fallback to load CoA
  sale_layout_category_hide_detail/tests/test_sale_layout_category_hide_detail.py
Labels: bot is merging ⏳

#323 [FIX] [16.0] sale_report_delivered: Fix unsigned_price_subtotal and unsigned_product_uom_qty using Valuation Layer Quantity first
  sale_report_delivered/reports/sale_report.py
Labels: needs review, approved, bot is merging ⏳

#324 [FIX] [16.0] sale_report_delivered: Exclude done moves with 0.0 quantities done
  sale_report_delivered/reports/sale_report.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
